### ISSUE TITLE
communication between bounded context

### ISSUE THREAD

**Issue by cephas44** [barsifedron/candid-cqrs#23]
Hello Sir barsifedron,
 really thank you for sharing experience with CQRS, but here I have a problem how to implement the events (C / S) between different bounded context.
for example for your platform with two bounded context
with different databases

1 loan (the item is loaned) loan:aggregationId
2 popular items (the most loaned items of the day)loanPopular:aggregationId

  help me and thank you

**Comment by barsifedron** [comment]
Your question is a bit vague.
From what I understand there could be two things you are trying to get answers on.

- Notify a separate bounded context. In such cases, this has nothing to do with CQRS since your CQRS architecture should be constrained within one domain context. Communicationg with another one would be done in the exact same manner you would do for a traditional Spring application. Most probably (but maybe not only) through events (sent through amazon, kfka etc....). An event listener on the other bounded context would take care of updating whatever you would like to update on that side.

- Create a projection (or update a counter) in a separate database. in this case your DOMAIN event listener can take care of things.

Some pseudo code can be found in this [PR](https://github.com/barsifedron/candid-cqrs/pull/25). I hope it is helpful.
Once you create an implementation for the interfaces and things work, it is up to you to choose how you want to proceed for your "pouplar items" use case.
You could have a query hitting your second db in this same service, have your front end hit another service which has access to the db etc..
Again, while we care a lot about the write side of things, we are pretty liberal when it comes to the read side.

Here I implemented a counter but it is up to you to chosose what to put in the second database.
You could  load all the loans of the day and recalculate everything after each loan if you wanted to (and performance is ok).
